// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: coordinator.proto

package pbcoordinator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MembershipChangeOpType int32

const (
	MembershipChangeOpType_ADD    MembershipChangeOpType = 0
	MembershipChangeOpType_REMOVE MembershipChangeOpType = 1
)

// Enum value maps for MembershipChangeOpType.
var (
	MembershipChangeOpType_name = map[int32]string{
		0: "ADD",
		1: "REMOVE",
	}
	MembershipChangeOpType_value = map[string]int32{
		"ADD":    0,
		"REMOVE": 1,
	}
)

func (x MembershipChangeOpType) Enum() *MembershipChangeOpType {
	p := new(MembershipChangeOpType)
	*p = x
	return p
}

func (x MembershipChangeOpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MembershipChangeOpType) Descriptor() protoreflect.EnumDescriptor {
	return file_coordinator_proto_enumTypes[0].Descriptor()
}

func (MembershipChangeOpType) Type() protoreflect.EnumType {
	return &file_coordinator_proto_enumTypes[0]
}

func (x MembershipChangeOpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MembershipChangeOpType.Descriptor instead.
func (MembershipChangeOpType) EnumDescriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{0}
}

type MembershipChangeOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        string                 `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	Op            MembershipChangeOpType `protobuf:"varint,2,opt,name=op,proto3,enum=coordinator.MembershipChangeOpType" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipChangeOperation) Reset() {
	*x = MembershipChangeOperation{}
	mi := &file_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipChangeOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipChangeOperation) ProtoMessage() {}

func (x *MembershipChangeOperation) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipChangeOperation.ProtoReflect.Descriptor instead.
func (*MembershipChangeOperation) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *MembershipChangeOperation) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

func (x *MembershipChangeOperation) GetOp() MembershipChangeOpType {
	if x != nil {
		return x.Op
	}
	return MembershipChangeOpType_ADD
}

var File_coordinator_proto protoreflect.FileDescriptor

const file_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x11coordinator.proto\x12\vcoordinator\"h\n" +
	"\x19MembershipChangeOperation\x12\x16\n" +
	"\x06member\x18\x01 \x01(\tR\x06member\x123\n" +
	"\x02op\x18\x02 \x01(\x0e2#.coordinator.MembershipChangeOpTypeR\x02op*-\n" +
	"\x16MembershipChangeOpType\x12\a\n" +
	"\x03ADD\x10\x00\x12\n" +
	"\n" +
	"\x06REMOVE\x10\x01B2Z0github.com/jmsadair/keychain/proto/pbcoordinatorb\x06proto3"

var (
	file_coordinator_proto_rawDescOnce sync.Once
	file_coordinator_proto_rawDescData []byte
)

func file_coordinator_proto_rawDescGZIP() []byte {
	file_coordinator_proto_rawDescOnce.Do(func() {
		file_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coordinator_proto_rawDesc), len(file_coordinator_proto_rawDesc)))
	})
	return file_coordinator_proto_rawDescData
}

var file_coordinator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_coordinator_proto_goTypes = []any{
	(MembershipChangeOpType)(0),       // 0: coordinator.MembershipChangeOpType
	(*MembershipChangeOperation)(nil), // 1: coordinator.MembershipChangeOperation
}
var file_coordinator_proto_depIdxs = []int32{
	0, // 0: coordinator.MembershipChangeOperation.op:type_name -> coordinator.MembershipChangeOpType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_coordinator_proto_init() }
func file_coordinator_proto_init() {
	if File_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coordinator_proto_rawDesc), len(file_coordinator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coordinator_proto_goTypes,
		DependencyIndexes: file_coordinator_proto_depIdxs,
		EnumInfos:         file_coordinator_proto_enumTypes,
		MessageInfos:      file_coordinator_proto_msgTypes,
	}.Build()
	File_coordinator_proto = out.File
	file_coordinator_proto_goTypes = nil
	file_coordinator_proto_depIdxs = nil
}
