// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: coordinator.proto

package pbcoordinator

import (
	pbchain "github.com/jmsadair/keychain/proto/pbchain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReadChainConfigurationRequest is a request to read the chain configuration.
type ReadChainConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChainConfigurationRequest) Reset() {
	*x = ReadChainConfigurationRequest{}
	mi := &file_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChainConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChainConfigurationRequest) ProtoMessage() {}

func (x *ReadChainConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChainConfigurationRequest.ProtoReflect.Descriptor instead.
func (*ReadChainConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{0}
}

// ReadChainConfigurationResponse is a response to a ReadChainConfigurationRequest.
type ReadChainConfigurationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A chain configuration.
	Configuration *pbchain.Configuration `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChainConfigurationResponse) Reset() {
	*x = ReadChainConfigurationResponse{}
	mi := &file_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChainConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChainConfigurationResponse) ProtoMessage() {}

func (x *ReadChainConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChainConfigurationResponse.ProtoReflect.Descriptor instead.
func (*ReadChainConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *ReadChainConfigurationResponse) GetConfiguration() *pbchain.Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

// An operation that adds a member to a chain.
type AddMemberOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the member being added.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The address of the member being added.
	Address       string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberOperation) Reset() {
	*x = AddMemberOperation{}
	mi := &file_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberOperation) ProtoMessage() {}

func (x *AddMemberOperation) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberOperation.ProtoReflect.Descriptor instead.
func (*AddMemberOperation) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *AddMemberOperation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddMemberOperation) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// An operation that removes a member from a chain.
type RemoveMemberOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the member being removed.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberOperation) Reset() {
	*x = RemoveMemberOperation{}
	mi := &file_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberOperation) ProtoMessage() {}

func (x *RemoveMemberOperation) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberOperation.ProtoReflect.Descriptor instead.
func (*RemoveMemberOperation) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveMemberOperation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// An operation to read the current chain membership configuration.
type ReadMembershipOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadMembershipOperation) Reset() {
	*x = ReadMembershipOperation{}
	mi := &file_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadMembershipOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMembershipOperation) ProtoMessage() {}

func (x *ReadMembershipOperation) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMembershipOperation.ProtoReflect.Descriptor instead.
func (*ReadMembershipOperation) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{4}
}

// An operation that will be replicated across a raft cluster.
type ReplicatedOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Operation:
	//
	//	*ReplicatedOperation_AddMember
	//	*ReplicatedOperation_RemoveMember
	//	*ReplicatedOperation_ReadMembership
	Operation     isReplicatedOperation_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicatedOperation) Reset() {
	*x = ReplicatedOperation{}
	mi := &file_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicatedOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicatedOperation) ProtoMessage() {}

func (x *ReplicatedOperation) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicatedOperation.ProtoReflect.Descriptor instead.
func (*ReplicatedOperation) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *ReplicatedOperation) GetOperation() isReplicatedOperation_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *ReplicatedOperation) GetAddMember() *AddMemberOperation {
	if x != nil {
		if x, ok := x.Operation.(*ReplicatedOperation_AddMember); ok {
			return x.AddMember
		}
	}
	return nil
}

func (x *ReplicatedOperation) GetRemoveMember() *RemoveMemberOperation {
	if x != nil {
		if x, ok := x.Operation.(*ReplicatedOperation_RemoveMember); ok {
			return x.RemoveMember
		}
	}
	return nil
}

func (x *ReplicatedOperation) GetReadMembership() *ReadMembershipOperation {
	if x != nil {
		if x, ok := x.Operation.(*ReplicatedOperation_ReadMembership); ok {
			return x.ReadMembership
		}
	}
	return nil
}

type isReplicatedOperation_Operation interface {
	isReplicatedOperation_Operation()
}

type ReplicatedOperation_AddMember struct {
	AddMember *AddMemberOperation `protobuf:"bytes,1,opt,name=add_member,json=addMember,proto3,oneof"`
}

type ReplicatedOperation_RemoveMember struct {
	RemoveMember *RemoveMemberOperation `protobuf:"bytes,2,opt,name=remove_member,json=removeMember,proto3,oneof"`
}

type ReplicatedOperation_ReadMembership struct {
	ReadMembership *ReadMembershipOperation `protobuf:"bytes,3,opt,name=read_membership,json=readMembership,proto3,oneof"`
}

func (*ReplicatedOperation_AddMember) isReplicatedOperation_Operation() {}

func (*ReplicatedOperation_RemoveMember) isReplicatedOperation_Operation() {}

func (*ReplicatedOperation_ReadMembership) isReplicatedOperation_Operation() {}

// Log is a log entry in the raft log.
type Log struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The index of this log entry.
	Index uint64 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// The election term of this log entry.
	Term uint64 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	// The type of this log entry.
	Type uint32 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	// The data of this log entry.
	Data []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	// The extensions for this log entry.
	Extensions []byte `protobuf:"bytes,5,opt,name=extensions,proto3" json:"extensions,omitempty"`
	// The time at which this log entry was appended to the log.
	AppendedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=appended_at,json=appendedAt,proto3" json:"appended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *Log) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Log) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Log) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Log) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Log) GetExtensions() []byte {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *Log) GetAppendedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AppendedAt
	}
	return nil
}

var File_coordinator_proto protoreflect.FileDescriptor

const file_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x11coordinator.proto\x12\vcoordinator\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\vchain.proto\"\x1f\n" +
	"\x1dReadChainConfigurationRequest\"\\\n" +
	"\x1eReadChainConfigurationResponse\x12:\n" +
	"\rconfiguration\x18\x01 \x01(\v2\x14.chain.ConfigurationR\rconfiguration\">\n" +
	"\x12AddMemberOperation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"'\n" +
	"\x15RemoveMemberOperation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\x17ReadMembershipOperation\"\x80\x02\n" +
	"\x13ReplicatedOperation\x12@\n" +
	"\n" +
	"add_member\x18\x01 \x01(\v2\x1f.coordinator.AddMemberOperationH\x00R\taddMember\x12I\n" +
	"\rremove_member\x18\x02 \x01(\v2\".coordinator.RemoveMemberOperationH\x00R\fremoveMember\x12O\n" +
	"\x0fread_membership\x18\x03 \x01(\v2$.coordinator.ReadMembershipOperationH\x00R\x0ereadMembershipB\v\n" +
	"\toperation\"\xb4\x01\n" +
	"\x03Log\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x12\n" +
	"\x04type\x18\x03 \x01(\rR\x04type\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1e\n" +
	"\n" +
	"extensions\x18\x05 \x01(\fR\n" +
	"extensions\x12;\n" +
	"\vappended_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"appendedAt2\x89\x01\n" +
	"\x12CoordinatorService\x12s\n" +
	"\x16ReadChainConfiguration\x12*.coordinator.ReadChainConfigurationRequest\x1a+.coordinator.ReadChainConfigurationResponse\"\x00B2Z0github.com/jmsadair/keychain/proto/pbcoordinatorb\x06proto3"

var (
	file_coordinator_proto_rawDescOnce sync.Once
	file_coordinator_proto_rawDescData []byte
)

func file_coordinator_proto_rawDescGZIP() []byte {
	file_coordinator_proto_rawDescOnce.Do(func() {
		file_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coordinator_proto_rawDesc), len(file_coordinator_proto_rawDesc)))
	})
	return file_coordinator_proto_rawDescData
}

var file_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_coordinator_proto_goTypes = []any{
	(*ReadChainConfigurationRequest)(nil),  // 0: coordinator.ReadChainConfigurationRequest
	(*ReadChainConfigurationResponse)(nil), // 1: coordinator.ReadChainConfigurationResponse
	(*AddMemberOperation)(nil),             // 2: coordinator.AddMemberOperation
	(*RemoveMemberOperation)(nil),          // 3: coordinator.RemoveMemberOperation
	(*ReadMembershipOperation)(nil),        // 4: coordinator.ReadMembershipOperation
	(*ReplicatedOperation)(nil),            // 5: coordinator.ReplicatedOperation
	(*Log)(nil),                            // 6: coordinator.Log
	(*pbchain.Configuration)(nil),          // 7: chain.Configuration
	(*timestamppb.Timestamp)(nil),          // 8: google.protobuf.Timestamp
}
var file_coordinator_proto_depIdxs = []int32{
	7, // 0: coordinator.ReadChainConfigurationResponse.configuration:type_name -> chain.Configuration
	2, // 1: coordinator.ReplicatedOperation.add_member:type_name -> coordinator.AddMemberOperation
	3, // 2: coordinator.ReplicatedOperation.remove_member:type_name -> coordinator.RemoveMemberOperation
	4, // 3: coordinator.ReplicatedOperation.read_membership:type_name -> coordinator.ReadMembershipOperation
	8, // 4: coordinator.Log.appended_at:type_name -> google.protobuf.Timestamp
	0, // 5: coordinator.CoordinatorService.ReadChainConfiguration:input_type -> coordinator.ReadChainConfigurationRequest
	1, // 6: coordinator.CoordinatorService.ReadChainConfiguration:output_type -> coordinator.ReadChainConfigurationResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_coordinator_proto_init() }
func file_coordinator_proto_init() {
	if File_coordinator_proto != nil {
		return
	}
	file_coordinator_proto_msgTypes[5].OneofWrappers = []any{
		(*ReplicatedOperation_AddMember)(nil),
		(*ReplicatedOperation_RemoveMember)(nil),
		(*ReplicatedOperation_ReadMembership)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coordinator_proto_rawDesc), len(file_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coordinator_proto_goTypes,
		DependencyIndexes: file_coordinator_proto_depIdxs,
		MessageInfos:      file_coordinator_proto_msgTypes,
	}.Build()
	File_coordinator_proto = out.File
	file_coordinator_proto_goTypes = nil
	file_coordinator_proto_depIdxs = nil
}
