// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: proto/proxy/proxy.proto

package proxy

import (
	api "github.com/jmsadair/keychainDB/proto/api"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_proxy_proxy_proto protoreflect.FileDescriptor

const file_proto_proxy_proxy_proto_rawDesc = "" +
	"\n" +
	"\x17proto/proxy/proxy.proto\x12\x05proxy\x1a\x13proto/api/api.proto\x1a\x1cgoogle/api/annotations.proto2\x8f\x01\n" +
	"\fProxyService\x12@\n" +
	"\x03Get\x12\x0f.api.GetRequest\x1a\x10.api.GetResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/keys/{key}\x12=\n" +
	"\x03Set\x12\x0f.api.SetRequest\x1a\x10.api.SetResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/keysB,Z*github.com/jmsadair/keychainDB/proto/proxyb\x06proto3"

var file_proto_proxy_proxy_proto_goTypes = []any{
	(*api.GetRequest)(nil),  // 0: api.GetRequest
	(*api.SetRequest)(nil),  // 1: api.SetRequest
	(*api.GetResponse)(nil), // 2: api.GetResponse
	(*api.SetResponse)(nil), // 3: api.SetResponse
}
var file_proto_proxy_proxy_proto_depIdxs = []int32{
	0, // 0: proxy.ProxyService.Get:input_type -> api.GetRequest
	1, // 1: proxy.ProxyService.Set:input_type -> api.SetRequest
	2, // 2: proxy.ProxyService.Get:output_type -> api.GetResponse
	3, // 3: proxy.ProxyService.Set:output_type -> api.SetResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_proxy_proxy_proto_init() }
func file_proto_proxy_proxy_proto_init() {
	if File_proto_proxy_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proxy_proxy_proto_rawDesc), len(file_proto_proxy_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proxy_proxy_proto_goTypes,
		DependencyIndexes: file_proto_proxy_proxy_proto_depIdxs,
	}.Build()
	File_proto_proxy_proxy_proto = out.File
	file_proto_proxy_proxy_proto_goTypes = nil
	file_proto_proxy_proxy_proto_depIdxs = nil
}
