// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: chain.proto

package pbchain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// KeyType contains all key types that can be propagated.
type KeyType int32

const (
	// All key-value pairs will be listed.
	KeyType_KEYTYPE_ALL KeyType = 0
	// Only committed key-value pairs will be listed.
	KeyType_KEYTYPE_COMMITTED KeyType = 1
	// Only dirty key-value pairs will be listed.
	KeyType_KEYTYPE_DIRTY KeyType = 2
)

// Enum value maps for KeyType.
var (
	KeyType_name = map[int32]string{
		0: "KEYTYPE_ALL",
		1: "KEYTYPE_COMMITTED",
		2: "KEYTYPE_DIRTY",
	}
	KeyType_value = map[string]int32{
		"KEYTYPE_ALL":       0,
		"KEYTYPE_COMMITTED": 1,
		"KEYTYPE_DIRTY":     2,
	}
)

func (x KeyType) Enum() *KeyType {
	p := new(KeyType)
	*p = x
	return p
}

func (x KeyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyType) Descriptor() protoreflect.EnumDescriptor {
	return file_chain_proto_enumTypes[0].Descriptor()
}

func (KeyType) Type() protoreflect.EnumType {
	return &file_chain_proto_enumTypes[0]
}

func (x KeyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyType.Descriptor instead.
func (KeyType) EnumDescriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{0}
}

// ChainMember represents a member of the chain with an ID and address.
type ChainMember struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique ID of the chain member.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The address of the chain member.
	Address       string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainMember) Reset() {
	*x = ChainMember{}
	mi := &file_chain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainMember) ProtoMessage() {}

func (x *ChainMember) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainMember.ProtoReflect.Descriptor instead.
func (*ChainMember) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{0}
}

func (x *ChainMember) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChainMember) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// Configuration contains the membership configuration of the chain.
type Configuration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The version of this configuration.
	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// The members of the chain with their IDs and addresses.
	Members       []*ChainMember `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_chain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{1}
}

func (x *Configuration) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Configuration) GetMembers() []*ChainMember {
	if x != nil {
		return x.Members
	}
	return nil
}

// UpdateConfigurationRequest is a request for a node to update its chain membership configuration.
type UpdateConfigurationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new configuration for the chain.
	Configuration *Configuration `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigurationRequest) Reset() {
	*x = UpdateConfigurationRequest{}
	mi := &file_chain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigurationRequest) ProtoMessage() {}

func (x *UpdateConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigurationRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateConfigurationRequest) GetConfiguration() *Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type UpdateConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigurationResponse) Reset() {
	*x = UpdateConfigurationResponse{}
	mi := &file_chain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigurationResponse) ProtoMessage() {}

func (x *UpdateConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigurationResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{3}
}

// WriteRequest is a request sent from one node of a chain to another to write a new version of a key.
type WriteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key being written.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The value for the key.
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// The version of the key.
	Version uint64 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// The configuration version.
	ConfigVersion uint64 `protobuf:"varint,4,opt,name=configVersion,proto3" json:"configVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_chain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{4}
}

func (x *WriteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *WriteRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WriteRequest) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

// WriteResponse is the response to a WriteRequest.
type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_chain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{5}
}

// ReadRequest is a request sent from one node of chain to another to read the value of a key.
type ReadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key being read.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The configuration version.
	ConfigVersion uint64 `protobuf:"varint,4,opt,name=configVersion,proto3" json:"configVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_chain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{6}
}

func (x *ReadRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReadRequest) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

// ReadResponse is the response to a ReadRequest and contains the value of the key read.
type ReadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The value of the key that was read.
	Value         []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_chain_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{7}
}

func (x *ReadResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// PropagateRequest is used to initiate a server-to-client stream of key-value pairs.
type PropagateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which type of key should be listed.
	KeyType KeyType `protobuf:"varint,1,opt,name=key_type,json=keyType,proto3,enum=chain.KeyType" json:"key_type,omitempty"`
	// The configuration version.
	ConfigVersion uint64 `protobuf:"varint,4,opt,name=configVersion,proto3" json:"configVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropagateRequest) Reset() {
	*x = PropagateRequest{}
	mi := &file_chain_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropagateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropagateRequest) ProtoMessage() {}

func (x *PropagateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropagateRequest.ProtoReflect.Descriptor instead.
func (*PropagateRequest) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{8}
}

func (x *PropagateRequest) GetKeyType() KeyType {
	if x != nil {
		return x.KeyType
	}
	return KeyType_KEYTYPE_ALL
}

func (x *PropagateRequest) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

// KeyValuePair is a key-value pair stored by a node of a chain.
type KeyValuePair struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The value associated with the key.
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// The version of the key.
	Version uint64 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// Whether or not this version of the key has been committed.
	IsCommitted   bool `protobuf:"varint,4,opt,name=isCommitted,proto3" json:"isCommitted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValuePair) Reset() {
	*x = KeyValuePair{}
	mi := &file_chain_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValuePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValuePair) ProtoMessage() {}

func (x *KeyValuePair) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValuePair.ProtoReflect.Descriptor instead.
func (*KeyValuePair) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{9}
}

func (x *KeyValuePair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValuePair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KeyValuePair) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *KeyValuePair) GetIsCommitted() bool {
	if x != nil {
		return x.IsCommitted
	}
	return false
}

// CommitRequest is a request to commit a version of a key.
type CommitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key being committed.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The version of the key being committed.
	Version uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// The configuration version.
	ConfigVersion uint64 `protobuf:"varint,4,opt,name=configVersion,proto3" json:"configVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_chain_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{10}
}

func (x *CommitRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CommitRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CommitRequest) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

// CommitResponse is a response to a CommitRequest.
type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_chain_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{11}
}

// PingRequest is a request to check if the node is alive and has an up-to-date configuration.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_chain_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{12}
}

// PingResponse is a response to a PingRequest.
type PingResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ConfigurationVersion uint64                 `protobuf:"varint,1,opt,name=configuration_version,json=configurationVersion,proto3" json:"configuration_version,omitempty"`
	Status               int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_chain_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_chain_proto_rawDescGZIP(), []int{13}
}

func (x *PingResponse) GetConfigurationVersion() uint64 {
	if x != nil {
		return x.ConfigurationVersion
	}
	return 0
}

func (x *PingResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_chain_proto protoreflect.FileDescriptor

const file_chain_proto_rawDesc = "" +
	"\n" +
	"\vchain.proto\x12\x05chain\"7\n" +
	"\vChainMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"W\n" +
	"\rConfiguration\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12,\n" +
	"\amembers\x18\x02 \x03(\v2\x12.chain.ChainMemberR\amembers\"X\n" +
	"\x1aUpdateConfigurationRequest\x12:\n" +
	"\rconfiguration\x18\x01 \x01(\v2\x14.chain.ConfigurationR\rconfiguration\"\x1d\n" +
	"\x1bUpdateConfigurationResponse\"v\n" +
	"\fWriteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x12$\n" +
	"\rconfigVersion\x18\x04 \x01(\x04R\rconfigVersion\"\x0f\n" +
	"\rWriteResponse\"E\n" +
	"\vReadRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\rconfigVersion\x18\x04 \x01(\x04R\rconfigVersion\"$\n" +
	"\fReadResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"c\n" +
	"\x10PropagateRequest\x12)\n" +
	"\bkey_type\x18\x01 \x01(\x0e2\x0e.chain.KeyTypeR\akeyType\x12$\n" +
	"\rconfigVersion\x18\x04 \x01(\x04R\rconfigVersion\"r\n" +
	"\fKeyValuePair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x12 \n" +
	"\visCommitted\x18\x04 \x01(\bR\visCommitted\"a\n" +
	"\rCommitRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12$\n" +
	"\rconfigVersion\x18\x04 \x01(\x04R\rconfigVersion\"\x10\n" +
	"\x0eCommitResponse\"\r\n" +
	"\vPingRequest\"[\n" +
	"\fPingResponse\x123\n" +
	"\x15configuration_version\x18\x01 \x01(\x04R\x14configurationVersion\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status*D\n" +
	"\aKeyType\x12\x0f\n" +
	"\vKEYTYPE_ALL\x10\x00\x12\x15\n" +
	"\x11KEYTYPE_COMMITTED\x10\x01\x12\x11\n" +
	"\rKEYTYPE_DIRTY\x10\x022\x82\x03\n" +
	"\fChainService\x124\n" +
	"\x05Write\x12\x13.chain.WriteRequest\x1a\x14.chain.WriteResponse\"\x00\x121\n" +
	"\x04Read\x12\x12.chain.ReadRequest\x1a\x13.chain.ReadResponse\"\x00\x127\n" +
	"\x06Commit\x12\x14.chain.CommitRequest\x1a\x15.chain.CommitResponse\"\x00\x12=\n" +
	"\tPropagate\x12\x17.chain.PropagateRequest\x1a\x13.chain.KeyValuePair\"\x000\x01\x12^\n" +
	"\x13UpdateConfiguration\x12!.chain.UpdateConfigurationRequest\x1a\".chain.UpdateConfigurationResponse\"\x00\x121\n" +
	"\x04Ping\x12\x12.chain.PingRequest\x1a\x13.chain.PingResponse\"\x00B,Z*github.com/jmsadair/keychain/proto/pbchainb\x06proto3"

var (
	file_chain_proto_rawDescOnce sync.Once
	file_chain_proto_rawDescData []byte
)

func file_chain_proto_rawDescGZIP() []byte {
	file_chain_proto_rawDescOnce.Do(func() {
		file_chain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chain_proto_rawDesc), len(file_chain_proto_rawDesc)))
	})
	return file_chain_proto_rawDescData
}

var file_chain_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chain_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_chain_proto_goTypes = []any{
	(KeyType)(0),                        // 0: chain.KeyType
	(*ChainMember)(nil),                 // 1: chain.ChainMember
	(*Configuration)(nil),               // 2: chain.Configuration
	(*UpdateConfigurationRequest)(nil),  // 3: chain.UpdateConfigurationRequest
	(*UpdateConfigurationResponse)(nil), // 4: chain.UpdateConfigurationResponse
	(*WriteRequest)(nil),                // 5: chain.WriteRequest
	(*WriteResponse)(nil),               // 6: chain.WriteResponse
	(*ReadRequest)(nil),                 // 7: chain.ReadRequest
	(*ReadResponse)(nil),                // 8: chain.ReadResponse
	(*PropagateRequest)(nil),            // 9: chain.PropagateRequest
	(*KeyValuePair)(nil),                // 10: chain.KeyValuePair
	(*CommitRequest)(nil),               // 11: chain.CommitRequest
	(*CommitResponse)(nil),              // 12: chain.CommitResponse
	(*PingRequest)(nil),                 // 13: chain.PingRequest
	(*PingResponse)(nil),                // 14: chain.PingResponse
}
var file_chain_proto_depIdxs = []int32{
	1,  // 0: chain.Configuration.members:type_name -> chain.ChainMember
	2,  // 1: chain.UpdateConfigurationRequest.configuration:type_name -> chain.Configuration
	0,  // 2: chain.PropagateRequest.key_type:type_name -> chain.KeyType
	5,  // 3: chain.ChainService.Write:input_type -> chain.WriteRequest
	7,  // 4: chain.ChainService.Read:input_type -> chain.ReadRequest
	11, // 5: chain.ChainService.Commit:input_type -> chain.CommitRequest
	9,  // 6: chain.ChainService.Propagate:input_type -> chain.PropagateRequest
	3,  // 7: chain.ChainService.UpdateConfiguration:input_type -> chain.UpdateConfigurationRequest
	13, // 8: chain.ChainService.Ping:input_type -> chain.PingRequest
	6,  // 9: chain.ChainService.Write:output_type -> chain.WriteResponse
	8,  // 10: chain.ChainService.Read:output_type -> chain.ReadResponse
	12, // 11: chain.ChainService.Commit:output_type -> chain.CommitResponse
	10, // 12: chain.ChainService.Propagate:output_type -> chain.KeyValuePair
	4,  // 13: chain.ChainService.UpdateConfiguration:output_type -> chain.UpdateConfigurationResponse
	14, // 14: chain.ChainService.Ping:output_type -> chain.PingResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_chain_proto_init() }
func file_chain_proto_init() {
	if File_chain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chain_proto_rawDesc), len(file_chain_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chain_proto_goTypes,
		DependencyIndexes: file_chain_proto_depIdxs,
		EnumInfos:         file_chain_proto_enumTypes,
		MessageInfos:      file_chain_proto_msgTypes,
	}.Build()
	File_chain_proto = out.File
	file_chain_proto_goTypes = nil
	file_chain_proto_depIdxs = nil
}
