// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: proto/chain/chain.proto

package chain

import (
	storage "github.com/jmsadair/keychain/proto/storage"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChainMember represents a member of the chain with an ID and address.
type ChainMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainMember) Reset() {
	*x = ChainMember{}
	mi := &file_proto_chain_chain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainMember) ProtoMessage() {}

func (x *ChainMember) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_chain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainMember.ProtoReflect.Descriptor instead.
func (*ChainMember) Descriptor() ([]byte, []int) {
	return file_proto_chain_chain_proto_rawDescGZIP(), []int{0}
}

func (x *ChainMember) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChainMember) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// Configuration contains the membership configuration of the chain.
type Configuration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Members       []*ChainMember         `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_proto_chain_chain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_chain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_proto_chain_chain_proto_rawDescGZIP(), []int{1}
}

func (x *Configuration) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Configuration) GetMembers() []*ChainMember {
	if x != nil {
		return x.Members
	}
	return nil
}

// UpdateConfigurationRequest is a request for a node to update its chain membership configuration.
type UpdateConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configuration *Configuration         `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigurationRequest) Reset() {
	*x = UpdateConfigurationRequest{}
	mi := &file_proto_chain_chain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigurationRequest) ProtoMessage() {}

func (x *UpdateConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_chain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigurationRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_chain_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateConfigurationRequest) GetConfiguration() *Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

// UpdateConfigurationResponse is a response to a UpdateConfigurationRequest.
type UpdateConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigurationResponse) Reset() {
	*x = UpdateConfigurationResponse{}
	mi := &file_proto_chain_chain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigurationResponse) ProtoMessage() {}

func (x *UpdateConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_chain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigurationResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_chain_proto_rawDescGZIP(), []int{3}
}

// ReplicateRequest is a request sent to the head of a chain to initiate replication of a key-value pair.
type ReplicateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ConfigVersion uint64                 `protobuf:"varint,3,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateRequest) Reset() {
	*x = ReplicateRequest{}
	mi := &file_proto_chain_chain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateRequest) ProtoMessage() {}

func (x *ReplicateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_chain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateRequest.ProtoReflect.Descriptor instead.
func (*ReplicateRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_chain_proto_rawDescGZIP(), []int{4}
}

func (x *ReplicateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReplicateRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ReplicateRequest) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

// ReplicateResponse is a response to a ReplicateRequest.
type ReplicateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateResponse) Reset() {
	*x = ReplicateResponse{}
	mi := &file_proto_chain_chain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateResponse) ProtoMessage() {}

func (x *ReplicateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_chain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateResponse.ProtoReflect.Descriptor instead.
func (*ReplicateResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_chain_proto_rawDescGZIP(), []int{5}
}

// WriteRequest is a request sent from one node of a chain to another to write a new version of a key.
type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	ConfigVersion uint64                 `protobuf:"varint,4,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_proto_chain_chain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_chain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_chain_proto_rawDescGZIP(), []int{6}
}

func (x *WriteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *WriteRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *WriteRequest) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

// WriteResponse is the response to a WriteRequest.
type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_proto_chain_chain_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_chain_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_chain_proto_rawDescGZIP(), []int{7}
}

// ReadRequest is a request sent from one node of chain to another to read the value of a key.
type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ConfigVersion uint64                 `protobuf:"varint,2,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	Forwarded     bool                   `protobuf:"varint,3,opt,name=forwarded,proto3" json:"forwarded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_proto_chain_chain_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_chain_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_chain_proto_rawDescGZIP(), []int{8}
}

func (x *ReadRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReadRequest) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *ReadRequest) GetForwarded() bool {
	if x != nil {
		return x.Forwarded
	}
	return false
}

// ReadResponse is the response to a ReadRequest and contains the value of the key read.
type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_proto_chain_chain_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_chain_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_chain_proto_rawDescGZIP(), []int{9}
}

func (x *ReadResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// PropagateRequest is used to initiate a server-to-client stream of key-value pairs.
type PropagateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyType       storage.KeyType        `protobuf:"varint,1,opt,name=key_type,json=keyType,proto3,enum=storage.KeyType" json:"key_type,omitempty"`
	ConfigVersion uint64                 `protobuf:"varint,2,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropagateRequest) Reset() {
	*x = PropagateRequest{}
	mi := &file_proto_chain_chain_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropagateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropagateRequest) ProtoMessage() {}

func (x *PropagateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_chain_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropagateRequest.ProtoReflect.Descriptor instead.
func (*PropagateRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_chain_proto_rawDescGZIP(), []int{10}
}

func (x *PropagateRequest) GetKeyType() storage.KeyType {
	if x != nil {
		return x.KeyType
	}
	return storage.KeyType(0)
}

func (x *PropagateRequest) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

// CommitRequest is a request to commit a version of a key.
type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	ConfigVersion uint64                 `protobuf:"varint,3,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_proto_chain_chain_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_chain_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_chain_proto_rawDescGZIP(), []int{11}
}

func (x *CommitRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CommitRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CommitRequest) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

// CommitResponse is a response to a CommitRequest.
type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_proto_chain_chain_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_chain_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_chain_proto_rawDescGZIP(), []int{12}
}

// PingRequest is a request to check if the node is alive and has an up-to-date configuration.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_chain_chain_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_chain_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_chain_proto_rawDescGZIP(), []int{13}
}

// PingResponse is a response to a PingRequest.
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion uint64                 `protobuf:"varint,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_chain_chain_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_chain_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_chain_proto_rawDescGZIP(), []int{14}
}

func (x *PingResponse) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *PingResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_proto_chain_chain_proto protoreflect.FileDescriptor

const file_proto_chain_chain_proto_rawDesc = "" +
	"\n" +
	"\x17proto/chain/chain.proto\x12\x05chain\x1a\x1bproto/storage/storage.proto\"7\n" +
	"\vChainMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"W\n" +
	"\rConfiguration\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12,\n" +
	"\amembers\x18\x02 \x03(\v2\x12.chain.ChainMemberR\amembers\"X\n" +
	"\x1aUpdateConfigurationRequest\x12:\n" +
	"\rconfiguration\x18\x01 \x01(\v2\x14.chain.ConfigurationR\rconfiguration\"\x1d\n" +
	"\x1bUpdateConfigurationResponse\"a\n" +
	"\x10ReplicateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12%\n" +
	"\x0econfig_version\x18\x03 \x01(\x04R\rconfigVersion\"\x13\n" +
	"\x11ReplicateResponse\"w\n" +
	"\fWriteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x12%\n" +
	"\x0econfig_version\x18\x04 \x01(\x04R\rconfigVersion\"\x0f\n" +
	"\rWriteResponse\"d\n" +
	"\vReadRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x0econfig_version\x18\x02 \x01(\x04R\rconfigVersion\x12\x1c\n" +
	"\tforwarded\x18\x03 \x01(\bR\tforwarded\"$\n" +
	"\fReadResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"f\n" +
	"\x10PropagateRequest\x12+\n" +
	"\bkey_type\x18\x01 \x01(\x0e2\x10.storage.KeyTypeR\akeyType\x12%\n" +
	"\x0econfig_version\x18\x02 \x01(\x04R\rconfigVersion\"b\n" +
	"\rCommitRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12%\n" +
	"\x0econfig_version\x18\x03 \x01(\x04R\rconfigVersion\"\x10\n" +
	"\x0eCommitResponse\"\r\n" +
	"\vPingRequest\"M\n" +
	"\fPingResponse\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\x04R\rconfigVersion\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status2\xc6\x03\n" +
	"\fChainService\x12@\n" +
	"\tReplicate\x12\x17.chain.ReplicateRequest\x1a\x18.chain.ReplicateResponse\"\x00\x124\n" +
	"\x05Write\x12\x13.chain.WriteRequest\x1a\x14.chain.WriteResponse\"\x00\x121\n" +
	"\x04Read\x12\x12.chain.ReadRequest\x1a\x13.chain.ReadResponse\"\x00\x127\n" +
	"\x06Commit\x12\x14.chain.CommitRequest\x1a\x15.chain.CommitResponse\"\x00\x12?\n" +
	"\tPropagate\x12\x17.chain.PropagateRequest\x1a\x15.storage.KeyValuePair\"\x000\x01\x12^\n" +
	"\x13UpdateConfiguration\x12!.chain.UpdateConfigurationRequest\x1a\".chain.UpdateConfigurationResponse\"\x00\x121\n" +
	"\x04Ping\x12\x12.chain.PingRequest\x1a\x13.chain.PingResponse\"\x00B*Z(github.com/jmsadair/keychain/proto/chainb\x06proto3"

var (
	file_proto_chain_chain_proto_rawDescOnce sync.Once
	file_proto_chain_chain_proto_rawDescData []byte
)

func file_proto_chain_chain_proto_rawDescGZIP() []byte {
	file_proto_chain_chain_proto_rawDescOnce.Do(func() {
		file_proto_chain_chain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chain_chain_proto_rawDesc), len(file_proto_chain_chain_proto_rawDesc)))
	})
	return file_proto_chain_chain_proto_rawDescData
}

var file_proto_chain_chain_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_chain_chain_proto_goTypes = []any{
	(*ChainMember)(nil),                 // 0: chain.ChainMember
	(*Configuration)(nil),               // 1: chain.Configuration
	(*UpdateConfigurationRequest)(nil),  // 2: chain.UpdateConfigurationRequest
	(*UpdateConfigurationResponse)(nil), // 3: chain.UpdateConfigurationResponse
	(*ReplicateRequest)(nil),            // 4: chain.ReplicateRequest
	(*ReplicateResponse)(nil),           // 5: chain.ReplicateResponse
	(*WriteRequest)(nil),                // 6: chain.WriteRequest
	(*WriteResponse)(nil),               // 7: chain.WriteResponse
	(*ReadRequest)(nil),                 // 8: chain.ReadRequest
	(*ReadResponse)(nil),                // 9: chain.ReadResponse
	(*PropagateRequest)(nil),            // 10: chain.PropagateRequest
	(*CommitRequest)(nil),               // 11: chain.CommitRequest
	(*CommitResponse)(nil),              // 12: chain.CommitResponse
	(*PingRequest)(nil),                 // 13: chain.PingRequest
	(*PingResponse)(nil),                // 14: chain.PingResponse
	(storage.KeyType)(0),                // 15: storage.KeyType
	(*storage.KeyValuePair)(nil),        // 16: storage.KeyValuePair
}
var file_proto_chain_chain_proto_depIdxs = []int32{
	0,  // 0: chain.Configuration.members:type_name -> chain.ChainMember
	1,  // 1: chain.UpdateConfigurationRequest.configuration:type_name -> chain.Configuration
	15, // 2: chain.PropagateRequest.key_type:type_name -> storage.KeyType
	4,  // 3: chain.ChainService.Replicate:input_type -> chain.ReplicateRequest
	6,  // 4: chain.ChainService.Write:input_type -> chain.WriteRequest
	8,  // 5: chain.ChainService.Read:input_type -> chain.ReadRequest
	11, // 6: chain.ChainService.Commit:input_type -> chain.CommitRequest
	10, // 7: chain.ChainService.Propagate:input_type -> chain.PropagateRequest
	2,  // 8: chain.ChainService.UpdateConfiguration:input_type -> chain.UpdateConfigurationRequest
	13, // 9: chain.ChainService.Ping:input_type -> chain.PingRequest
	5,  // 10: chain.ChainService.Replicate:output_type -> chain.ReplicateResponse
	7,  // 11: chain.ChainService.Write:output_type -> chain.WriteResponse
	9,  // 12: chain.ChainService.Read:output_type -> chain.ReadResponse
	12, // 13: chain.ChainService.Commit:output_type -> chain.CommitResponse
	16, // 14: chain.ChainService.Propagate:output_type -> storage.KeyValuePair
	3,  // 15: chain.ChainService.UpdateConfiguration:output_type -> chain.UpdateConfigurationResponse
	14, // 16: chain.ChainService.Ping:output_type -> chain.PingResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_chain_chain_proto_init() }
func file_proto_chain_chain_proto_init() {
	if File_proto_chain_chain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chain_chain_proto_rawDesc), len(file_proto_chain_chain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chain_chain_proto_goTypes,
		DependencyIndexes: file_proto_chain_chain_proto_depIdxs,
		MessageInfos:      file_proto_chain_chain_proto_msgTypes,
	}.Build()
	File_proto_chain_chain_proto = out.File
	file_proto_chain_chain_proto_goTypes = nil
	file_proto_chain_chain_proto_depIdxs = nil
}
