// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: proto/raft/raft.proto

package raft

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AppendEntriesRequest is the command used to append entries to the replicated log.
type AppendEntriesRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RpcHeader         *RpcHeader             `protobuf:"bytes,1,opt,name=rpc_header,json=rpcHeader,proto3" json:"rpc_header,omitempty"`
	Term              uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Leader            []byte                 `protobuf:"bytes,3,opt,name=leader,proto3" json:"leader,omitempty"`
	PrevLogEntry      uint64                 `protobuf:"varint,4,opt,name=prev_log_entry,json=prevLogEntry,proto3" json:"prev_log_entry,omitempty"`
	PrevLogTerm       uint64                 `protobuf:"varint,5,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	LeaderCommitIndex uint64                 `protobuf:"varint,6,opt,name=leader_commit_index,json=leaderCommitIndex,proto3" json:"leader_commit_index,omitempty"`
	Entries           []*Log                 `protobuf:"bytes,7,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AppendEntriesRequest) Reset() {
	*x = AppendEntriesRequest{}
	mi := &file_proto_raft_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesRequest) ProtoMessage() {}

func (x *AppendEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_raft_raft_proto_rawDescGZIP(), []int{0}
}

func (x *AppendEntriesRequest) GetRpcHeader() *RpcHeader {
	if x != nil {
		return x.RpcHeader
	}
	return nil
}

func (x *AppendEntriesRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesRequest) GetLeader() []byte {
	if x != nil {
		return x.Leader
	}
	return nil
}

func (x *AppendEntriesRequest) GetPrevLogEntry() uint64 {
	if x != nil {
		return x.PrevLogEntry
	}
	return 0
}

func (x *AppendEntriesRequest) GetPrevLogTerm() uint64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntriesRequest) GetLeaderCommitIndex() uint64 {
	if x != nil {
		return x.LeaderCommitIndex
	}
	return 0
}

func (x *AppendEntriesRequest) GetEntries() []*Log {
	if x != nil {
		return x.Entries
	}
	return nil
}

// AppendEntriesResponse is the response returned from an AppendEntriesRequest.
type AppendEntriesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RpcHeader      *RpcHeader             `protobuf:"bytes,1,opt,name=rpc_header,json=rpcHeader,proto3" json:"rpc_header,omitempty"`
	Term           uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	LastLog        uint64                 `protobuf:"varint,3,opt,name=last_log,json=lastLog,proto3" json:"last_log,omitempty"`
	Success        bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	NoRetryBackoff bool                   `protobuf:"varint,5,opt,name=no_retry_backoff,json=noRetryBackoff,proto3" json:"no_retry_backoff,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AppendEntriesResponse) Reset() {
	*x = AppendEntriesResponse{}
	mi := &file_proto_raft_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResponse) ProtoMessage() {}

func (x *AppendEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_raft_raft_proto_rawDescGZIP(), []int{1}
}

func (x *AppendEntriesResponse) GetRpcHeader() *RpcHeader {
	if x != nil {
		return x.RpcHeader
	}
	return nil
}

func (x *AppendEntriesResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesResponse) GetLastLog() uint64 {
	if x != nil {
		return x.LastLog
	}
	return 0
}

func (x *AppendEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AppendEntriesResponse) GetNoRetryBackoff() bool {
	if x != nil {
		return x.NoRetryBackoff
	}
	return false
}

// RequestPreVoteRequest is the command used by a candidate to ask a Raft peer for a vote in an election.
type RequestPreVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcHeader     *RpcHeader             `protobuf:"bytes,1,opt,name=rpc_header,json=rpcHeader,proto3" json:"rpc_header,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	LastLogIndex  uint64                 `protobuf:"varint,3,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm   uint64                 `protobuf:"varint,4,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPreVoteRequest) Reset() {
	*x = RequestPreVoteRequest{}
	mi := &file_proto_raft_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPreVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPreVoteRequest) ProtoMessage() {}

func (x *RequestPreVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPreVoteRequest.ProtoReflect.Descriptor instead.
func (*RequestPreVoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_raft_raft_proto_rawDescGZIP(), []int{2}
}

func (x *RequestPreVoteRequest) GetRpcHeader() *RpcHeader {
	if x != nil {
		return x.RpcHeader
	}
	return nil
}

func (x *RequestPreVoteRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestPreVoteRequest) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestPreVoteRequest) GetLastLogTerm() uint64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

// RequestPreVoteResponse is the response returned from a RequestPreVoteRequest.
type RequestPreVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcHeader     *RpcHeader             `protobuf:"bytes,1,opt,name=rpc_header,json=rpcHeader,proto3" json:"rpc_header,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Granted       bool                   `protobuf:"varint,3,opt,name=granted,proto3" json:"granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPreVoteResponse) Reset() {
	*x = RequestPreVoteResponse{}
	mi := &file_proto_raft_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPreVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPreVoteResponse) ProtoMessage() {}

func (x *RequestPreVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPreVoteResponse.ProtoReflect.Descriptor instead.
func (*RequestPreVoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_raft_raft_proto_rawDescGZIP(), []int{3}
}

func (x *RequestPreVoteResponse) GetRpcHeader() *RpcHeader {
	if x != nil {
		return x.RpcHeader
	}
	return nil
}

func (x *RequestPreVoteResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestPreVoteResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

// RequestVoteRequest is the command used by a candidate to ask a peer for a vote in an election.
type RequestVoteRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RpcHeader          *RpcHeader             `protobuf:"bytes,1,opt,name=rpc_header,json=rpcHeader,proto3" json:"rpc_header,omitempty"`
	Term               uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Candidate          []byte                 `protobuf:"bytes,3,opt,name=candidate,proto3" json:"candidate,omitempty"`
	LastLogIndex       uint64                 `protobuf:"varint,4,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm        uint64                 `protobuf:"varint,5,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	LeadershipTransfer bool                   `protobuf:"varint,6,opt,name=leadership_transfer,json=leadershipTransfer,proto3" json:"leadership_transfer,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RequestVoteRequest) Reset() {
	*x = RequestVoteRequest{}
	mi := &file_proto_raft_raft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteRequest) ProtoMessage() {}

func (x *RequestVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_raft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteRequest.ProtoReflect.Descriptor instead.
func (*RequestVoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_raft_raft_proto_rawDescGZIP(), []int{4}
}

func (x *RequestVoteRequest) GetRpcHeader() *RpcHeader {
	if x != nil {
		return x.RpcHeader
	}
	return nil
}

func (x *RequestVoteRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteRequest) GetCandidate() []byte {
	if x != nil {
		return x.Candidate
	}
	return nil
}

func (x *RequestVoteRequest) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteRequest) GetLastLogTerm() uint64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

func (x *RequestVoteRequest) GetLeadershipTransfer() bool {
	if x != nil {
		return x.LeadershipTransfer
	}
	return false
}

// RequestVoteResponse is the response returned from a RequestVoteRequest.
type RequestVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcHeader     *RpcHeader             `protobuf:"bytes,1,opt,name=rpc_header,json=rpcHeader,proto3" json:"rpc_header,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Peers         []byte                 `protobuf:"bytes,3,opt,name=peers,proto3" json:"peers,omitempty"`
	Granted       bool                   `protobuf:"varint,4,opt,name=granted,proto3" json:"granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteResponse) Reset() {
	*x = RequestVoteResponse{}
	mi := &file_proto_raft_raft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteResponse) ProtoMessage() {}

func (x *RequestVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_raft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteResponse.ProtoReflect.Descriptor instead.
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_raft_raft_proto_rawDescGZIP(), []int{5}
}

func (x *RequestVoteResponse) GetRpcHeader() *RpcHeader {
	if x != nil {
		return x.RpcHeader
	}
	return nil
}

func (x *RequestVoteResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteResponse) GetPeers() []byte {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *RequestVoteResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

// InstallSnapshotRequest is the command sent to a peer to bootstrap its log (and state machine) from a snapshot on another peer.
type InstallSnapshotRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RpcHeader          *RpcHeader             `protobuf:"bytes,1,opt,name=rpc_header,json=rpcHeader,proto3" json:"rpc_header,omitempty"`
	SnapshotVersion    int32                  `protobuf:"varint,2,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`
	Term               uint64                 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	Leader             []byte                 `protobuf:"bytes,4,opt,name=leader,proto3" json:"leader,omitempty"`
	LastLogIndex       uint64                 `protobuf:"varint,5,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm        uint64                 `protobuf:"varint,6,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	Peers              []byte                 `protobuf:"bytes,7,opt,name=peers,proto3" json:"peers,omitempty"`
	Configuration      []byte                 `protobuf:"bytes,8,opt,name=configuration,proto3" json:"configuration,omitempty"`
	ConfigurationIndex uint64                 `protobuf:"varint,9,opt,name=configuration_index,json=configurationIndex,proto3" json:"configuration_index,omitempty"`
	Size               int64                  `protobuf:"varint,10,opt,name=size,proto3" json:"size,omitempty"`
	Data               []byte                 `protobuf:"bytes,11,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InstallSnapshotRequest) Reset() {
	*x = InstallSnapshotRequest{}
	mi := &file_proto_raft_raft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotRequest) ProtoMessage() {}

func (x *InstallSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_raft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotRequest.ProtoReflect.Descriptor instead.
func (*InstallSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_raft_raft_proto_rawDescGZIP(), []int{6}
}

func (x *InstallSnapshotRequest) GetRpcHeader() *RpcHeader {
	if x != nil {
		return x.RpcHeader
	}
	return nil
}

func (x *InstallSnapshotRequest) GetSnapshotVersion() int32 {
	if x != nil {
		return x.SnapshotVersion
	}
	return 0
}

func (x *InstallSnapshotRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *InstallSnapshotRequest) GetLeader() []byte {
	if x != nil {
		return x.Leader
	}
	return nil
}

func (x *InstallSnapshotRequest) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *InstallSnapshotRequest) GetLastLogTerm() uint64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

func (x *InstallSnapshotRequest) GetPeers() []byte {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *InstallSnapshotRequest) GetConfiguration() []byte {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *InstallSnapshotRequest) GetConfigurationIndex() uint64 {
	if x != nil {
		return x.ConfigurationIndex
	}
	return 0
}

func (x *InstallSnapshotRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *InstallSnapshotRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// InstallSnapshotResponse is the response returned from an InstallSnapshotRequest.
type InstallSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcHeader     *RpcHeader             `protobuf:"bytes,1,opt,name=rpc_header,json=rpcHeader,proto3" json:"rpc_header,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallSnapshotResponse) Reset() {
	*x = InstallSnapshotResponse{}
	mi := &file_proto_raft_raft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotResponse) ProtoMessage() {}

func (x *InstallSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_raft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotResponse.ProtoReflect.Descriptor instead.
func (*InstallSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_raft_raft_proto_rawDescGZIP(), []int{7}
}

func (x *InstallSnapshotResponse) GetRpcHeader() *RpcHeader {
	if x != nil {
		return x.RpcHeader
	}
	return nil
}

func (x *InstallSnapshotResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *InstallSnapshotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// TimeoutNowRequest is the command used by a leader to signal another server to start an election.
type TimeoutNowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcHeader     *RpcHeader             `protobuf:"bytes,1,opt,name=rpc_header,json=rpcHeader,proto3" json:"rpc_header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeoutNowRequest) Reset() {
	*x = TimeoutNowRequest{}
	mi := &file_proto_raft_raft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutNowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutNowRequest) ProtoMessage() {}

func (x *TimeoutNowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_raft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutNowRequest.ProtoReflect.Descriptor instead.
func (*TimeoutNowRequest) Descriptor() ([]byte, []int) {
	return file_proto_raft_raft_proto_rawDescGZIP(), []int{8}
}

func (x *TimeoutNowRequest) GetRpcHeader() *RpcHeader {
	if x != nil {
		return x.RpcHeader
	}
	return nil
}

// TimeoutNowResponse is the response to TimeoutNowRequest.
type TimeoutNowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcHeader     *RpcHeader             `protobuf:"bytes,1,opt,name=rpc_header,json=rpcHeader,proto3" json:"rpc_header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeoutNowResponse) Reset() {
	*x = TimeoutNowResponse{}
	mi := &file_proto_raft_raft_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutNowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutNowResponse) ProtoMessage() {}

func (x *TimeoutNowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_raft_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutNowResponse.ProtoReflect.Descriptor instead.
func (*TimeoutNowResponse) Descriptor() ([]byte, []int) {
	return file_proto_raft_raft_proto_rawDescGZIP(), []int{9}
}

func (x *TimeoutNowResponse) GetRpcHeader() *RpcHeader {
	if x != nil {
		return x.RpcHeader
	}
	return nil
}

// Log represents an entry in the replicated log.
type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Type          uint32                 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Extensions    []byte                 `protobuf:"bytes,5,opt,name=extensions,proto3" json:"extensions,omitempty"`
	AppendedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=appended_at,json=appendedAt,proto3" json:"appended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_proto_raft_raft_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_raft_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_proto_raft_raft_proto_rawDescGZIP(), []int{10}
}

func (x *Log) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Log) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Log) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Log) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Log) GetExtensions() []byte {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *Log) GetAppendedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AppendedAt
	}
	return nil
}

// RPCHeader is a common sub-structure used to pass along protocol version and other information about the cluster.
// For older Raft implementations before versioning was added this will default to a zero-valued structure when
// read by newer Raft versions.
type RpcHeader struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion int32                  `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Id              []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Addr            []byte                 `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RpcHeader) Reset() {
	*x = RpcHeader{}
	mi := &file_proto_raft_raft_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcHeader) ProtoMessage() {}

func (x *RpcHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_raft_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcHeader.ProtoReflect.Descriptor instead.
func (*RpcHeader) Descriptor() ([]byte, []int) {
	return file_proto_raft_raft_proto_rawDescGZIP(), []int{11}
}

func (x *RpcHeader) GetProtocolVersion() int32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *RpcHeader) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *RpcHeader) GetAddr() []byte {
	if x != nil {
		return x.Addr
	}
	return nil
}

var File_proto_raft_raft_proto protoreflect.FileDescriptor

const file_proto_raft_raft_proto_rawDesc = "" +
	"\n" +
	"\x15proto/raft/raft.proto\x12\x04raft\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x02\n" +
	"\x14AppendEntriesRequest\x12.\n" +
	"\n" +
	"rpc_header\x18\x01 \x01(\v2\x0f.raft.RpcHeaderR\trpcHeader\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x16\n" +
	"\x06leader\x18\x03 \x01(\fR\x06leader\x12$\n" +
	"\x0eprev_log_entry\x18\x04 \x01(\x04R\fprevLogEntry\x12\"\n" +
	"\rprev_log_term\x18\x05 \x01(\x04R\vprevLogTerm\x12.\n" +
	"\x13leader_commit_index\x18\x06 \x01(\x04R\x11leaderCommitIndex\x12#\n" +
	"\aentries\x18\a \x03(\v2\t.raft.LogR\aentries\"\xba\x01\n" +
	"\x15AppendEntriesResponse\x12.\n" +
	"\n" +
	"rpc_header\x18\x01 \x01(\v2\x0f.raft.RpcHeaderR\trpcHeader\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x19\n" +
	"\blast_log\x18\x03 \x01(\x04R\alastLog\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12(\n" +
	"\x10no_retry_backoff\x18\x05 \x01(\bR\x0enoRetryBackoff\"\xa5\x01\n" +
	"\x15RequestPreVoteRequest\x12.\n" +
	"\n" +
	"rpc_header\x18\x01 \x01(\v2\x0f.raft.RpcHeaderR\trpcHeader\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12$\n" +
	"\x0elast_log_index\x18\x03 \x01(\x04R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x04 \x01(\x04R\vlastLogTerm\"v\n" +
	"\x16RequestPreVoteResponse\x12.\n" +
	"\n" +
	"rpc_header\x18\x01 \x01(\v2\x0f.raft.RpcHeaderR\trpcHeader\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x18\n" +
	"\agranted\x18\x03 \x01(\bR\agranted\"\xf1\x01\n" +
	"\x12RequestVoteRequest\x12.\n" +
	"\n" +
	"rpc_header\x18\x01 \x01(\v2\x0f.raft.RpcHeaderR\trpcHeader\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x1c\n" +
	"\tcandidate\x18\x03 \x01(\fR\tcandidate\x12$\n" +
	"\x0elast_log_index\x18\x04 \x01(\x04R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x05 \x01(\x04R\vlastLogTerm\x12/\n" +
	"\x13leadership_transfer\x18\x06 \x01(\bR\x12leadershipTransfer\"\x89\x01\n" +
	"\x13RequestVoteResponse\x12.\n" +
	"\n" +
	"rpc_header\x18\x01 \x01(\v2\x0f.raft.RpcHeaderR\trpcHeader\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x14\n" +
	"\x05peers\x18\x03 \x01(\fR\x05peers\x12\x18\n" +
	"\agranted\x18\x04 \x01(\bR\agranted\"\xfe\x02\n" +
	"\x16InstallSnapshotRequest\x12.\n" +
	"\n" +
	"rpc_header\x18\x01 \x01(\v2\x0f.raft.RpcHeaderR\trpcHeader\x12)\n" +
	"\x10snapshot_version\x18\x02 \x01(\x05R\x0fsnapshotVersion\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\x12\x16\n" +
	"\x06leader\x18\x04 \x01(\fR\x06leader\x12$\n" +
	"\x0elast_log_index\x18\x05 \x01(\x04R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x06 \x01(\x04R\vlastLogTerm\x12\x14\n" +
	"\x05peers\x18\a \x01(\fR\x05peers\x12$\n" +
	"\rconfiguration\x18\b \x01(\fR\rconfiguration\x12/\n" +
	"\x13configuration_index\x18\t \x01(\x04R\x12configurationIndex\x12\x12\n" +
	"\x04size\x18\n" +
	" \x01(\x03R\x04size\x12\x12\n" +
	"\x04data\x18\v \x01(\fR\x04data\"w\n" +
	"\x17InstallSnapshotResponse\x12.\n" +
	"\n" +
	"rpc_header\x18\x01 \x01(\v2\x0f.raft.RpcHeaderR\trpcHeader\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"C\n" +
	"\x11TimeoutNowRequest\x12.\n" +
	"\n" +
	"rpc_header\x18\x01 \x01(\v2\x0f.raft.RpcHeaderR\trpcHeader\"D\n" +
	"\x12TimeoutNowResponse\x12.\n" +
	"\n" +
	"rpc_header\x18\x01 \x01(\v2\x0f.raft.RpcHeaderR\trpcHeader\"\xb4\x01\n" +
	"\x03Log\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x12\n" +
	"\x04type\x18\x03 \x01(\rR\x04type\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1e\n" +
	"\n" +
	"extensions\x18\x05 \x01(\fR\n" +
	"extensions\x12;\n" +
	"\vappended_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"appendedAt\"Z\n" +
	"\tRpcHeader\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\x05R\x0fprotocolVersion\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\fR\x04addr2\xdd\x03\n" +
	"\vRaftService\x12J\n" +
	"\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x1b.raft.AppendEntriesResponse\"\x00\x12V\n" +
	"\x15AppendEntriesPipeline\x12\x1a.raft.AppendEntriesRequest\x1a\x1b.raft.AppendEntriesResponse\"\x00(\x010\x01\x12D\n" +
	"\vRequestVote\x12\x18.raft.RequestVoteRequest\x1a\x19.raft.RequestVoteResponse\"\x00\x12M\n" +
	"\x0eRequestPreVote\x12\x1b.raft.RequestPreVoteRequest\x1a\x1c.raft.RequestPreVoteResponse\"\x00\x12R\n" +
	"\x0fInstallSnapshot\x12\x1c.raft.InstallSnapshotRequest\x1a\x1d.raft.InstallSnapshotResponse\"\x00(\x01\x12A\n" +
	"\n" +
	"TimeoutNow\x12\x17.raft.TimeoutNowRequest\x1a\x18.raft.TimeoutNowResponse\"\x00B+Z)github.com/jmsadair/keychainDB/proto/raftb\x06proto3"

var (
	file_proto_raft_raft_proto_rawDescOnce sync.Once
	file_proto_raft_raft_proto_rawDescData []byte
)

func file_proto_raft_raft_proto_rawDescGZIP() []byte {
	file_proto_raft_raft_proto_rawDescOnce.Do(func() {
		file_proto_raft_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_raft_raft_proto_rawDesc), len(file_proto_raft_raft_proto_rawDesc)))
	})
	return file_proto_raft_raft_proto_rawDescData
}

var file_proto_raft_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_raft_raft_proto_goTypes = []any{
	(*AppendEntriesRequest)(nil),    // 0: raft.AppendEntriesRequest
	(*AppendEntriesResponse)(nil),   // 1: raft.AppendEntriesResponse
	(*RequestPreVoteRequest)(nil),   // 2: raft.RequestPreVoteRequest
	(*RequestPreVoteResponse)(nil),  // 3: raft.RequestPreVoteResponse
	(*RequestVoteRequest)(nil),      // 4: raft.RequestVoteRequest
	(*RequestVoteResponse)(nil),     // 5: raft.RequestVoteResponse
	(*InstallSnapshotRequest)(nil),  // 6: raft.InstallSnapshotRequest
	(*InstallSnapshotResponse)(nil), // 7: raft.InstallSnapshotResponse
	(*TimeoutNowRequest)(nil),       // 8: raft.TimeoutNowRequest
	(*TimeoutNowResponse)(nil),      // 9: raft.TimeoutNowResponse
	(*Log)(nil),                     // 10: raft.Log
	(*RpcHeader)(nil),               // 11: raft.RpcHeader
	(*timestamppb.Timestamp)(nil),   // 12: google.protobuf.Timestamp
}
var file_proto_raft_raft_proto_depIdxs = []int32{
	11, // 0: raft.AppendEntriesRequest.rpc_header:type_name -> raft.RpcHeader
	10, // 1: raft.AppendEntriesRequest.entries:type_name -> raft.Log
	11, // 2: raft.AppendEntriesResponse.rpc_header:type_name -> raft.RpcHeader
	11, // 3: raft.RequestPreVoteRequest.rpc_header:type_name -> raft.RpcHeader
	11, // 4: raft.RequestPreVoteResponse.rpc_header:type_name -> raft.RpcHeader
	11, // 5: raft.RequestVoteRequest.rpc_header:type_name -> raft.RpcHeader
	11, // 6: raft.RequestVoteResponse.rpc_header:type_name -> raft.RpcHeader
	11, // 7: raft.InstallSnapshotRequest.rpc_header:type_name -> raft.RpcHeader
	11, // 8: raft.InstallSnapshotResponse.rpc_header:type_name -> raft.RpcHeader
	11, // 9: raft.TimeoutNowRequest.rpc_header:type_name -> raft.RpcHeader
	11, // 10: raft.TimeoutNowResponse.rpc_header:type_name -> raft.RpcHeader
	12, // 11: raft.Log.appended_at:type_name -> google.protobuf.Timestamp
	0,  // 12: raft.RaftService.AppendEntries:input_type -> raft.AppendEntriesRequest
	0,  // 13: raft.RaftService.AppendEntriesPipeline:input_type -> raft.AppendEntriesRequest
	4,  // 14: raft.RaftService.RequestVote:input_type -> raft.RequestVoteRequest
	2,  // 15: raft.RaftService.RequestPreVote:input_type -> raft.RequestPreVoteRequest
	6,  // 16: raft.RaftService.InstallSnapshot:input_type -> raft.InstallSnapshotRequest
	8,  // 17: raft.RaftService.TimeoutNow:input_type -> raft.TimeoutNowRequest
	1,  // 18: raft.RaftService.AppendEntries:output_type -> raft.AppendEntriesResponse
	1,  // 19: raft.RaftService.AppendEntriesPipeline:output_type -> raft.AppendEntriesResponse
	5,  // 20: raft.RaftService.RequestVote:output_type -> raft.RequestVoteResponse
	3,  // 21: raft.RaftService.RequestPreVote:output_type -> raft.RequestPreVoteResponse
	7,  // 22: raft.RaftService.InstallSnapshot:output_type -> raft.InstallSnapshotResponse
	9,  // 23: raft.RaftService.TimeoutNow:output_type -> raft.TimeoutNowResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_raft_raft_proto_init() }
func file_proto_raft_raft_proto_init() {
	if File_proto_raft_raft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_raft_raft_proto_rawDesc), len(file_proto_raft_raft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_raft_raft_proto_goTypes,
		DependencyIndexes: file_proto_raft_raft_proto_depIdxs,
		MessageInfos:      file_proto_raft_raft_proto_msgTypes,
	}.Build()
	File_proto_raft_raft_proto = out.File
	file_proto_raft_raft_proto_goTypes = nil
	file_proto_raft_raft_proto_depIdxs = nil
}
